[package]
name = "passterm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.28.0", features = ["Win32_System_Console", "Win32_Foundation"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"