[package]
name = "passterm"
version = "1.0.2"
edition = "2021"
authors = [
	"Kyle Schreiber <kyle@80x24.net>",
]
readme = "README.md"
license = "Apache-2.0"
description = "Read passwords from terminal"
repository = "https://github.com/finfet/passterm"
documentation = "https://docs.rs/passterm/"
homepage = "https://github.com/finfet/passterm"
keywords = ["read", "password", "security", "pass", "getpass"]
categories = ["command-line-interface"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[target.'cfg(windows)'.dependencies]
windows = { version = "0.29.0", features = ["Win32_System_Console", "Win32_Foundation", "Win32_Storage_FileSystem"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2"
